language: cpp
addons:
  apt:
    packages: &1
    - cmake
    - swig
    - libasound2-dev
    - libopenshot-audio-dev
    - libmagick++-dev
    - libunittest++-dev
    - libzmq3-dev
    - qtbase5-dev
    - qtmultimedia5-dev
    - doxygen
    - graphviz
    - curl
    - libfdk-aac-dev
    - libavcodec-dev
    - libavformat-dev
    - libavdevice-dev
    - libavutil-dev
    - libavfilter-dev
    - libswscale-dev
    - libpostproc-dev
    - libavresample-dev
    - libswresample-dev

jobs:
  include:
  - name: FFmpeg 4 GCC (Ubuntu 18.04 Bionic)
    env:
    - BUILD_VERSION=ffmpeg4
    - TEST_TARGET=test
    os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        sources:
        - sourceline: ppa:openshot.developers/libopenshot-daily
        - sourceline: ppa:beineri/opt-qt-5.12.3-bionic
        - sourceline: ppa:jonathonf/ffmpeg-4
        packages:
        - *1
        - qt5-default
        - libjsoncpp-dev
        - libavcodec58
        - libavformat58
        - libavdevice58
        - libavutil56
        - libavfilter7
        - libswscale5
        - libpostproc55
        - libavresample4
        - libswresample3
  - name: FFmpeg 3.4 Clang (Ubuntu 18.04 Bionic)
    env:
    - BUILD_VERSION=clang_ffmpeg34
    - TEST_TARGET=test
    os: linux
    dist: bionic
    compiler: clang
    addons:
      apt:
        sources:
        - sourceline: ppa:openshot.developers/libopenshot-daily
        - sourceline: ppa:beineri/opt-qt-5.12.3-bionic
        packages:
        - *1
        - qt5-default
        - libomp-dev
  - name: macOS Latest
    env:
    - BUILD_VERSION=ffmpeg4
    - TEST_TARGET="test"
    - CMAKE_EXTRA_ARGS="-DENABLE_RUBY=0"
    - Qt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5
    os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        update: true
        packages:
        - cmake
        - libomp
        - qt
        - imagemagick
        - libvpx
        - x264
        - x265
        - fdk-aac
        - fdk-aac-encoder
        - ffmpeg
        - zeromq
        - swig
        - unittest-cpp
        - rust

before_script:
  - mkdir build
  - if [ "x${TRAVIS_OS_NAME}" = "xosx" ]; then eval $(brew --env|grep -i cmake); fi
  - if [ "x${TRAVIS_OS_NAME}" = "xosx" ]; then pushd libopenshot-audio; cmake -DCMAKE_BUILD_TYPE=Debug $(brew diy --name libopenshot-audio --version 0.2.0-dev2) .; cmake --build . -- VERBOSE=1; cmake --build . --target install -- VERBOSE=1; brew link libopenshot-audio; popd; fi
  - if [ "x${TRAVIS_OS_NAME}" = "xosx" ]; then git clone https://github.com/zeromq/cppzmq; pushd cppzmq; cmake $(brew diy --verbose --name cppzmq --version $(sh ./version.sh)) -DCMAKE_BUILD_TYPE=Debug -DENABLE_DRAFTS=0 .; cmake --build .; cmake --build . --target install; brew link --verbose cppzmq; popd; fi

script:
  - pushd build
  - if [ "x${TRAVIS_OS_NAME}" = "xosx" ]; then echo "${CMAKE_EXTRA_ARGS}"; fi
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install-x64 ${CMAKE_EXTRA_ARGS} ../libopenshot
  - cmake --build . -- VERBOSE=1
  - cmake --build . --target ${TEST_TARGET} -- VERBOSE=1
  - cmake --build . --target install -- VERBOSE=1
  - cd ..

after_failure:
  - cat build/CMakeCache.txt
  - if [ "x${TRAVIS_OS_NAME}" = "xosx" ]; then brew config; brew doctor; fi

