language: cpp
compiler: gcc

# This section uses a rather esoteric (and tricky!) feature of YAML,
# &aliases and *anchors, to build package lists out of sublists without
# repeating their contents. Basically, '&name' creates an alias for the
# given data, which can then be referenced using the anchor '*name'.
addons:
  apt:
    packages: &p_common  # Packages common to all Ubuntu builds
    - cmake
    - swig
    - libasound2-dev
    - libmagick++-dev
    - libunittest++-dev
    - libzmq3-dev
    - qtbase5-dev
    - qtmultimedia5-dev
    - doxygen
    - graphviz
    - curl
    packages: &ff_common  # Common set of FFmpeg packages
    - *p_common
    - libfdk-aac-dev
    - libavcodec-dev
    - libavformat-dev
    - libavdevice-dev
    - libavutil-dev
    - libavfilter-dev
    - libswscale-dev
    - libpostproc-dev
    - libavresample-dev
    - libswresample-dev
  homebrew:
    taps:
    - jmuncaster/homebrew-header-only
    packages: &homebrew
    - gcc
    - swig
    - unittest-cpp
    - rust
    - qt
    - libomp
    - imagemagick
    - libvpx
    - x264
    - x265
    - fdk-aac
    - fdk-aac-encoder
    - ffmpeg
    - cppzmq

jobs:
  include:

    - name: "FFmpeg 4 GCC (Ubuntu 18.04 Bionic)"
      env:
        - BUILD_VERSION=ffmpeg4
        - CMAKE_EXTRA_ARGS="-DOpenShotAudio_ROOT=install-x64"
        - TEST_TARGET=test
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
          - sourceline: 'ppa:openshot.developers/libopenshot-daily'
          - sourceline: 'ppa:beineri/opt-qt-5.12.3-bionic'
          - sourceline: 'ppa:jonathonf/ffmpeg-4'
          packages:
          - *ff_common
          - qt5-default
          - libjsoncpp-dev
          - libavcodec58
          - libavformat58
          - libavdevice58
          - libavutil56
          - libavfilter7
          - libswscale5
          - libpostproc55
          - libavresample4
          - libswresample3

    - name: "FFmpeg 3.4 Clang (Ubuntu 18.04 Bionic)"
      env:
        - BUILD_VERSION=clang_ffmpeg34
        - CMAKE_EXTRA_ARGS="-DOpenShotAudio_ROOT=install-x64"
        - TEST_TARGET=test
      os: linux
      dist: bionic
      compiler: clang
      addons:
        apt:
          sources:
          - sourceline: 'ppa:openshot.developers/libopenshot-daily'
          - sourceline: 'ppa:beineri/opt-qt-5.12.3-bionic'
          packages:
          - *ff_common
          - qt5-default
          - libomp-dev
          
    - name: "macOS Latest"
      env:
        - BUILD_VERSION=ffmpeg4
        - CMAKE_EXTRA_ARGS="-DOpenShotAudio_ROOT=install-x64"
        - TEST_TARGET="test"
        - Qt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5
      os: osx
      osx_image: xcode10.3
      addons:
        homebrew:
          taps:
          - jmuncaster/homebrew-header-only
          packages:
          - gcc
          - swig
          - unittest-cpp
          - rust
          - qt
          - libomp
          - imagemagick
          - libvpx
          - x264
          - x265
          - fdk-aac
          - fdk-aac-encoder
          - ffmpeg
          - cppzmq

script:
  - mkdir build; mkdir libopenshot-audio-build
  - pushd libopenshot-audio-build; cmake -DCMAKE_INSTALL_PREFIX=../build/install-x64 ../libopenshot-audio; cmake --build . -- VERBOSE=1; make install VERBOSE=1; popd
  - if [ "x${TRAVIS_OS_NAME}" = "xosx" ]; then export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DFFmpeg_ROOT=$(brew --prefix ffmpeg)"; fi
  - cd build
  - cmake -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX=install-x64 ${CMAKE_EXTRA_ARGS} ../libopenshot
  - cmake --build . -- VERBOSE=1
  - cmake --build . --target ${TEST_TARGET} -- VERBOSE=1
  - make install VERBOSE=1
  - cd ..

