# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        shell: [bash, 'msys2 {0}']
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
        exclude:
          - shell: 'msys2 {0}'
          - os: windows-latest
            shell: bash
        include:
          - os: windows-latest
            shell: 'msys2 {0}'
    defaults: 
      run:
        shell: ${{ matrix.shell }}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - if: ${{ runner.os == 'windows' }}
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: false
          install: >-
            mingw-w64-x86_64-clang
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $PATH; echo $CC; echo $CXX

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pip3 install distro
          python3 -mdistro
