# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: '${{ matrix.os.os }}-latest'
    strategy:
      matrix:
        os:
          - { os: windows, shell: msys2 }
          - { os: ubuntu,  shell: bash  }
          - { os: macos,   shell: bash  }
        comp:
          - { cc: gcc,   cxx: g++ }
          - { cc: clang, cxx: clang++ }
    defaults:
      run:
        shell: '${{ matrix.os.shell }} {0}'
    env:
      CC: ${{ matrix.comp.cc }}
      CXX: ${{ matrix.comp.cxx }}
    steps:
      - if: ${{ runner.os == 'windows' }}
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: false
          install: >-
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-python
            mingw-w64-x86_64-python-pip
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access i
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $PATH; echo $CC; echo $CXX

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          python -mpip install distro
          python -mdistro
