on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
        runme:
          - NaN
          - undefined
          - yes
          - no
          - false
          - 0
          - 1
          - -0
          - null

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.java }}'
          cache: 'maven'
      - if: matrix.runme
        run: echo "${{ matrix.runme }} evaluates true"
      - if: '! matrix.runme'
        run: echo "${{ matrix.runme }} evaluates false"
      - name: "Check maven"
        run: |
          cd java/mytest
          echo "$(which mvn)"
